#!/bin/bash
# opencga-data-upload 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.


main() {
    echo "Summary of data provided:"
    echo "- Input VCF(s): ${input_vcf}"
    echo "- Metadata: '${input_metadata}'"
    echo "- Credentials file: '${input_credentials}'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".
    # Fill in your application code here.

    # Define a function for reading credentials.json
    read_cred () {
        user=$(jq .user "${1}")
        password=$(jq .password "${1}")
        host=$(jq .host "${1}")
        opencga_cli_file_id=$(jq .opencga_cli_file_id "${1}")
    }

    # Download inputs in the "in" folder
    mkdir -p /home/dnanexus/in

    # Get the original name of the VCF file
    vcf_name=$(dx describe "${input_vcf}" --name)

    echo "Downloading input files"
    dx download "${input_vcf}" -o /home/dnanexus/in/"${vcf_name}"
    dx download "${input_metadata}" -o /home/dnanexus/in/metadata.json
    dx download "${input_credentials}" -o /home/dnanexus/in/credentials.json

    # Read credentials file
    read_cred /home/dnanexus/in/credentials.json

    # Download openCGA CLI and uncompress
    echo "Getting the OpenCGA CLI"
    dx download "${opencga_cli_file_id}"
    cli_name=$(dx describe "${opencga_cli_file_id}" --name)
    mkdir -p /home/dnanexus/opencga_cli && tar -xzf ${cli_name} -C /home/dnanexus/opencga_cli --strip-components 1
    opencga_cli=$(ls /home/dnanexus/opencga_cli/bin)
    if [ "${opencga_cli}" != "opencga.sh" ]; then
      dx-jobutil-report-error "opencga.sh not found in the provided cli folder. As a result no further actions can be performed"
    else
      echo "${opencga_cli} in ${cli_name} is ready to use"
    fi

    # Get DNAnexus file ID
    echo "Obtaining VCF file ID"
    dnanexus_fid=$(dx describe "${input_vcf}" --json | jq -r '.id')

    # Install python dependencies
    echo "Installing requirements"
    pip install --user -r /home/dnanexus/requirements.txt -q

    # Run opencga load
    echo "Launching OpenCGA upload"
    opencga_cmd="python3 opencga_upload_and_index.py --metadata /home/dnanexus/in/metadata.json \
                                                     --credentials /home/dnanexus/in/credentials.json \
                                                     --vcf /home/dnanexus/in/${vcf_name} \
                                                     --cli /home/dnanexus/opencga_cli/bin/opencga.sh \
                                                     --dnanexus_fid ${dnanexus_fid}"
    echo "${opencga_cmd}"
    eval "${opencga_cmd}"

    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:

    if [ -f /home/dnanexus/opencga_loader.err ]; then
        if [ -s /home/dnanexus/opencga_loader.err ]; then
            cat
                dx-jobutil-report-error "ERROR: Failed to load VCF ${vcf_name} into OpenCGA. See
                /home/dnanexus/opencga_loader.err for more details."
        else
            echo "VCF ${vcf_name} was loaded successfully to OpenCGA"
        fi
    fi

    cat opencga_loader.log

    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

    output=$(dx upload opencga_loader.log --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output output "$output" --class=file
}
