#!/bin/bash
# opencga-data-upload 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.


main() {
    echo "Summary of data provided:"
    echo "- Input VCF(s): ${input_vcf}"
    echo "- Metadata: '${input_metadata}'"
    echo "- Credentials file: '${input_credentials}'"
    echo "- Project: '${input_project}'"
    echo "- Study: '${input_study}'"
    echo "- Somatic: '${input_somatic}'"
    echo "- Multifile: '${input_mutifile}'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".
    # Fill in your application code here.

    # Define a function for reading credentials.json
    read_cred () {
        user=$(jq .user "${1}")
        password=$(jq .password "${1}")
        host=$(jq .host "${1}")
        opencga_cli_file_id=$(jq -r .opencga_cli_file_id "${1}")
    }

    # Download inputs in the "in" folder
    mkdir -p /home/dnanexus/in

    # Get the original name of the VCF file
    vcf_name=$(dx describe "${input_vcf}" --name)
    echo "${vcf_name}"

    # Download inputs in parallel
    time dx-download-all-inputs --parallel

    # array inputs end up in subdirectories (i.e. ~/in/array-input/0/), flatten to parent dir
    find ~/in/input_vcf -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/in/input_vcf
    find ~/in/input_metadata -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/in/input_metadata
    # location of input_credentials is ~/in/input_credentials/

    # Read credentials file
    read_cred ~/in/input_credentials/${input_credentials_name}

    # Download openCGA CLI and uncompress
    echo "Getting the OpenCGA CLI"
    dx download ${opencga_cli_file_id}
    cli_name=$(dx describe "${opencga_cli_file_id}" --name)
    mkdir -p /home/dnanexus/opencga_cli && tar -xzf ${cli_name} -C /home/dnanexus/opencga_cli --strip-components 1
    opencga_cli=$(ls /home/dnanexus/opencga_cli/bin)
    if [ "${opencga_cli}" != "opencga.sh" ]; then
      dx-jobutil-report-error "opencga.sh not found in the provided cli folder. As a result no further actions can be performed"
    else
      echo "${opencga_cli} in ${cli_name} is ready to use"
    fi

    # Get DNAnexus file ID
    echo "Obtaining VCF file ID"
    dnanexus_fid=$(dx describe "${input_vcf}" --json | jq -r '.id')

    # Install python dependencies
    echo "Installing requirements"
    pip install pyopencga-2.4.9-py3-none-any.whl

    # Run opencga load
    echo "Launching OpenCGA upload"
    opencga_cmd="python3 opencga_upload_and_index.py --credentials ~/in/input_credentials/${input_credentials_name} \
                                                     --vcf /home/dnanexus/in/${vcf_name} \
                                                     --cli /home/dnanexus/opencga_cli/bin/opencga.sh \
                                                     --dnanexus_fid ${dnanexus_fid} "
    if [ -n "${input_metadata}" ]; then
      opencga_cmd+=" --metadata /home/dnanexus/in/metadata.zip"
    fi
    if [ -n "${input_project}" ]; then
      opencga_cmd+=" --project ${input_project}"
    fi
    if [ -n "${input_study}" ]; then
      opencga_cmd+=" --study ${input_study}"
    fi
    if [ "${input_somatic}" = true ]; then
      opencga_cmd+=" --somatic"
    fi
    if [ "${input_multifile}" = true ]; then
      opencga_cmd+=" --multifile"
    fi
    echo "${opencga_cmd}"
    eval "${opencga_cmd}"

    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:

    if [ -f /home/dnanexus/opencga_loader.err ]; then
        if [ -s /home/dnanexus/opencga_loader.err ]; then
            cat
                dx-jobutil-report-error "ERROR: Failed to load VCF ${vcf_name} into OpenCGA. See
                /home/dnanexus/opencga_loader.err for more details."
        else
            echo "VCF ${vcf_name} was loaded successfully to OpenCGA"
        fi
    fi

    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

    opencga_out=$(dx upload /home/dnanexus/opencga_loader.out --brief)
    opencga_err=$(dx upload /home/dnanexus/opencga_loader.err --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.


    dx-jobutil-add-output opencga_out "${opencga_out}" --class=file
    dx-jobutil-add-output opencga_err "${opencga_err}" --class=file
}
